import {
  FrictionIcon,
  HueIcon,
  IrrationalityIcon,
  LightIcon,
  LightnessIcon,
  RotateSpeedIcon,
  SaturationIcon,
  SwitchDurationIcon,
  TensionIcon,
  ZoomDistanceIcon,
} from "./MenuIcons";

export const thumbIconMap = {
  irrationality: IrrationalityIcon,
  light: LightIcon,
  rotateSpeed: RotateSpeedIcon,
  hue: HueIcon,
  lightness: LightnessIcon,
  saturation: SaturationIcon,
  switchDuration: SwitchDurationIcon,
  zoomDistance: ZoomDistanceIcon,
  tension: TensionIcon,
  friction: FrictionIcon,
  earSize: "/icons/earSize.jpg",
  eyeSize: "/icons/eyeSize.jpg",
  eyeX: "/icons/eyeX.jpg",
  eyeY: "/icons/eyeY.jpg",
  eyeZ: "/icons/eyeZ.jpg",
  meshaSize: "/icons/meshaSize.jpg",
  moustacheSize: "/icons/moustacheSize.jpg",
  noseSize: "/icons/noseSize.jpg",
  teethSize: "/icons/teethSize.jpg",
  tongueSize: "/icons/tongueSize.jpg",
};
